// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZelezniceSrbije.Data;

#nullable disable

namespace ZelezniceSrbije.Migrations
{
    [DbContext(typeof(VozAppContext))]
    partial class VozAppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Raspored", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Linija_id")
                        .HasColumnType("int")
                        .HasColumnName("linija_id");

                    b.Property<int?>("Sablon_id")
                        .HasColumnType("int")
                        .HasColumnName("sablon_id");

                    b.Property<int>("Voz_id")
                        .HasColumnType("int")
                        .HasColumnName("voz_id");

                    b.Property<DateTime>("Vreme_polaska")
                        .HasColumnType("datetime2")
                        .HasColumnName("vreme_polaska");

                    b.HasKey("Id");

                    b.HasIndex("Linija_id");

                    b.HasIndex("Sablon_id");

                    b.HasIndex("Voz_id");

                    b.ToTable("Raspored", (string)null);
                });

            modelBuilder.Entity("ZelezniceSrbije.Models.Karta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cena")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Cena");

                    b.Property<DateTime?>("Datum_ocitavanja")
                        .HasColumnType("datetime2")
                        .HasColumnName("Datum_ocitavanja");

                    b.Property<string>("Kondukter")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Kondukter");

                    b.Property<string>("Linija")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Linija");

                    b.Property<bool>("Ocitana")
                        .HasColumnType("bit")
                        .HasColumnName("Ocitana");

                    b.Property<string>("Odrediste")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Odrediste");

                    b.Property<string>("Polaziste")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Polaziste");

                    b.Property<int>("Putnik_id")
                        .HasColumnType("int")
                        .HasColumnName("Putnik_id");

                    b.Property<Guid>("Qr_token")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Qr_token");

                    b.Property<int>("Raspored_id")
                        .HasColumnType("int")
                        .HasColumnName("Raspored_id");

                    b.Property<string>("Tip_voza")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Tip_voza");

                    b.Property<int>("Trajanje_min")
                        .HasColumnType("int")
                        .HasColumnName("Trajanje_min");

                    b.Property<DateTime>("Vreme_dolaska")
                        .HasColumnType("datetime2")
                        .HasColumnName("Vreme_dolaska");

                    b.Property<DateTime>("Vreme_polaska")
                        .HasColumnType("datetime2")
                        .HasColumnName("Vreme_polaska");

                    b.HasKey("Id");

                    b.HasIndex("Putnik_id");

                    b.HasIndex("Raspored_id");

                    b.ToTable("Karta", (string)null);
                });

            modelBuilder.Entity("ZelezniceSrbije.Models.Korisnik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("email");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("ime");

                    b.Property<string>("Lozinka")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("prezime");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Korisnik", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("ZelezniceSrbije.Models.Linija", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cena_po_minutu")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Linija", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cena_po_minutu = 12,
                            Naziv = "Beograd Centar – Novi Sad"
                        },
                        new
                        {
                            Id = 2,
                            Cena_po_minutu = 12,
                            Naziv = "Novi Sad – Beograd Centar"
                        },
                        new
                        {
                            Id = 3,
                            Cena_po_minutu = 18,
                            Naziv = "Subotica – Beograd Centar"
                        },
                        new
                        {
                            Id = 4,
                            Cena_po_minutu = 16,
                            Naziv = "Beograd Centar – Subotica"
                        },
                        new
                        {
                            Id = 5,
                            Cena_po_minutu = 16,
                            Naziv = "Subotica – Beograd Centar"
                        },
                        new
                        {
                            Id = 6,
                            Cena_po_minutu = 8,
                            Naziv = "Zemun – Niš"
                        },
                        new
                        {
                            Id = 7,
                            Cena_po_minutu = 8,
                            Naziv = "Niš – Zemun"
                        },
                        new
                        {
                            Id = 8,
                            Cena_po_minutu = 8,
                            Naziv = "Zemun – Pančevo"
                        },
                        new
                        {
                            Id = 9,
                            Cena_po_minutu = 8,
                            Naziv = "Pančevo – Zemun"
                        },
                        new
                        {
                            Id = 10,
                            Cena_po_minutu = 8,
                            Naziv = "Zemun – Vršac"
                        },
                        new
                        {
                            Id = 11,
                            Cena_po_minutu = 8,
                            Naziv = "Vršac – Zemun"
                        },
                        new
                        {
                            Id = 12,
                            Cena_po_minutu = 8,
                            Naziv = "Zemun – Šid"
                        },
                        new
                        {
                            Id = 13,
                            Cena_po_minutu = 8,
                            Naziv = "Šid – Zemun"
                        },
                        new
                        {
                            Id = 14,
                            Cena_po_minutu = 8,
                            Naziv = "Novi Sad – Šid"
                        },
                        new
                        {
                            Id = 15,
                            Cena_po_minutu = 8,
                            Naziv = "Šid – Novi Sad"
                        },
                        new
                        {
                            Id = 16,
                            Cena_po_minutu = 8,
                            Naziv = "Zemun – Užice"
                        },
                        new
                        {
                            Id = 17,
                            Cena_po_minutu = 8,
                            Naziv = "Užice – Zemun"
                        },
                        new
                        {
                            Id = 18,
                            Cena_po_minutu = 8,
                            Naziv = "Zemun – Valjevo"
                        },
                        new
                        {
                            Id = 19,
                            Cena_po_minutu = 8,
                            Naziv = "Valjevo – Zemun"
                        },
                        new
                        {
                            Id = 20,
                            Cena_po_minutu = 12,
                            Naziv = "Beograd Centar - Vršac"
                        });
                });

            modelBuilder.Entity("ZelezniceSrbije.Models.RasporedSablon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktivan")
                        .HasColumnType("bit")
                        .HasColumnName("aktivan");

                    b.Property<int>("Linija_id")
                        .HasColumnType("int")
                        .HasColumnName("linija_id");

                    b.Property<int>("Voz_id")
                        .HasColumnType("int")
                        .HasColumnName("voz_id");

                    b.Property<TimeSpan>("Vreme_polaska_time")
                        .HasColumnType("time")
                        .HasColumnName("vreme_polaska_time");

                    b.HasKey("Id");

                    b.HasIndex("Linija_id");

                    b.HasIndex("Voz_id");

                    b.ToTable("RasporedSablon", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aktivan = true,
                            Linija_id = 1,
                            Voz_id = 1,
                            Vreme_polaska_time = new TimeSpan(0, 7, 0, 0, 0)
                        },
                        new
                        {
                            Id = 2,
                            Aktivan = true,
                            Linija_id = 1,
                            Voz_id = 2,
                            Vreme_polaska_time = new TimeSpan(0, 13, 0, 0, 0)
                        },
                        new
                        {
                            Id = 3,
                            Aktivan = true,
                            Linija_id = 1,
                            Voz_id = 1,
                            Vreme_polaska_time = new TimeSpan(0, 19, 0, 0, 0)
                        },
                        new
                        {
                            Id = 4,
                            Aktivan = true,
                            Linija_id = 2,
                            Voz_id = 2,
                            Vreme_polaska_time = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 5,
                            Aktivan = true,
                            Linija_id = 2,
                            Voz_id = 1,
                            Vreme_polaska_time = new TimeSpan(0, 15, 0, 0, 0)
                        },
                        new
                        {
                            Id = 6,
                            Aktivan = true,
                            Linija_id = 2,
                            Voz_id = 2,
                            Vreme_polaska_time = new TimeSpan(0, 21, 0, 0, 0)
                        },
                        new
                        {
                            Id = 7,
                            Aktivan = true,
                            Linija_id = 3,
                            Voz_id = 1,
                            Vreme_polaska_time = new TimeSpan(0, 6, 0, 0, 0)
                        },
                        new
                        {
                            Id = 8,
                            Aktivan = true,
                            Linija_id = 3,
                            Voz_id = 2,
                            Vreme_polaska_time = new TimeSpan(0, 14, 0, 0, 0)
                        },
                        new
                        {
                            Id = 9,
                            Aktivan = true,
                            Linija_id = 4,
                            Voz_id = 2,
                            Vreme_polaska_time = new TimeSpan(0, 9, 30, 0, 0)
                        },
                        new
                        {
                            Id = 10,
                            Aktivan = true,
                            Linija_id = 4,
                            Voz_id = 1,
                            Vreme_polaska_time = new TimeSpan(0, 17, 30, 0, 0)
                        },
                        new
                        {
                            Id = 11,
                            Aktivan = true,
                            Linija_id = 5,
                            Voz_id = 1,
                            Vreme_polaska_time = new TimeSpan(0, 7, 15, 0, 0)
                        },
                        new
                        {
                            Id = 12,
                            Aktivan = true,
                            Linija_id = 5,
                            Voz_id = 2,
                            Vreme_polaska_time = new TimeSpan(0, 16, 15, 0, 0)
                        },
                        new
                        {
                            Id = 13,
                            Aktivan = true,
                            Linija_id = 6,
                            Voz_id = 1,
                            Vreme_polaska_time = new TimeSpan(0, 5, 0, 0, 0)
                        },
                        new
                        {
                            Id = 14,
                            Aktivan = true,
                            Linija_id = 6,
                            Voz_id = 2,
                            Vreme_polaska_time = new TimeSpan(0, 15, 0, 0, 0)
                        },
                        new
                        {
                            Id = 15,
                            Aktivan = true,
                            Linija_id = 7,
                            Voz_id = 2,
                            Vreme_polaska_time = new TimeSpan(0, 9, 30, 0, 0)
                        },
                        new
                        {
                            Id = 16,
                            Aktivan = true,
                            Linija_id = 7,
                            Voz_id = 1,
                            Vreme_polaska_time = new TimeSpan(0, 19, 30, 0, 0)
                        },
                        new
                        {
                            Id = 17,
                            Aktivan = true,
                            Linija_id = 8,
                            Voz_id = 1,
                            Vreme_polaska_time = new TimeSpan(0, 6, 30, 0, 0)
                        },
                        new
                        {
                            Id = 18,
                            Aktivan = true,
                            Linija_id = 8,
                            Voz_id = 2,
                            Vreme_polaska_time = new TimeSpan(0, 12, 30, 0, 0)
                        },
                        new
                        {
                            Id = 19,
                            Aktivan = true,
                            Linija_id = 8,
                            Voz_id = 1,
                            Vreme_polaska_time = new TimeSpan(0, 18, 30, 0, 0)
                        },
                        new
                        {
                            Id = 20,
                            Aktivan = true,
                            Linija_id = 9,
                            Voz_id = 2,
                            Vreme_polaska_time = new TimeSpan(0, 7, 30, 0, 0)
                        },
                        new
                        {
                            Id = 21,
                            Aktivan = true,
                            Linija_id = 9,
                            Voz_id = 1,
                            Vreme_polaska_time = new TimeSpan(0, 13, 30, 0, 0)
                        },
                        new
                        {
                            Id = 22,
                            Aktivan = true,
                            Linija_id = 9,
                            Voz_id = 2,
                            Vreme_polaska_time = new TimeSpan(0, 19, 30, 0, 0)
                        },
                        new
                        {
                            Id = 23,
                            Aktivan = true,
                            Linija_id = 10,
                            Voz_id = 1,
                            Vreme_polaska_time = new TimeSpan(0, 7, 0, 0, 0)
                        },
                        new
                        {
                            Id = 24,
                            Aktivan = true,
                            Linija_id = 10,
                            Voz_id = 2,
                            Vreme_polaska_time = new TimeSpan(0, 14, 0, 0, 0)
                        },
                        new
                        {
                            Id = 25,
                            Aktivan = true,
                            Linija_id = 11,
                            Voz_id = 2,
                            Vreme_polaska_time = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 26,
                            Aktivan = true,
                            Linija_id = 11,
                            Voz_id = 1,
                            Vreme_polaska_time = new TimeSpan(0, 16, 0, 0, 0)
                        },
                        new
                        {
                            Id = 27,
                            Aktivan = true,
                            Linija_id = 12,
                            Voz_id = 1,
                            Vreme_polaska_time = new TimeSpan(0, 8, 0, 0, 0)
                        },
                        new
                        {
                            Id = 28,
                            Aktivan = true,
                            Linija_id = 12,
                            Voz_id = 2,
                            Vreme_polaska_time = new TimeSpan(0, 16, 0, 0, 0)
                        },
                        new
                        {
                            Id = 29,
                            Aktivan = true,
                            Linija_id = 13,
                            Voz_id = 2,
                            Vreme_polaska_time = new TimeSpan(0, 10, 15, 0, 0)
                        },
                        new
                        {
                            Id = 30,
                            Aktivan = true,
                            Linija_id = 13,
                            Voz_id = 1,
                            Vreme_polaska_time = new TimeSpan(0, 18, 15, 0, 0)
                        },
                        new
                        {
                            Id = 31,
                            Aktivan = true,
                            Linija_id = 14,
                            Voz_id = 1,
                            Vreme_polaska_time = new TimeSpan(0, 7, 45, 0, 0)
                        },
                        new
                        {
                            Id = 32,
                            Aktivan = true,
                            Linija_id = 14,
                            Voz_id = 2,
                            Vreme_polaska_time = new TimeSpan(0, 13, 45, 0, 0)
                        },
                        new
                        {
                            Id = 33,
                            Aktivan = true,
                            Linija_id = 15,
                            Voz_id = 2,
                            Vreme_polaska_time = new TimeSpan(0, 10, 0, 0, 0)
                        },
                        new
                        {
                            Id = 34,
                            Aktivan = true,
                            Linija_id = 15,
                            Voz_id = 1,
                            Vreme_polaska_time = new TimeSpan(0, 16, 0, 0, 0)
                        },
                        new
                        {
                            Id = 35,
                            Aktivan = true,
                            Linija_id = 16,
                            Voz_id = 1,
                            Vreme_polaska_time = new TimeSpan(0, 6, 0, 0, 0)
                        },
                        new
                        {
                            Id = 36,
                            Aktivan = true,
                            Linija_id = 16,
                            Voz_id = 2,
                            Vreme_polaska_time = new TimeSpan(0, 14, 15, 0, 0)
                        },
                        new
                        {
                            Id = 37,
                            Aktivan = true,
                            Linija_id = 17,
                            Voz_id = 2,
                            Vreme_polaska_time = new TimeSpan(0, 9, 45, 0, 0)
                        },
                        new
                        {
                            Id = 38,
                            Aktivan = true,
                            Linija_id = 17,
                            Voz_id = 1,
                            Vreme_polaska_time = new TimeSpan(0, 18, 0, 0, 0)
                        },
                        new
                        {
                            Id = 39,
                            Aktivan = true,
                            Linija_id = 18,
                            Voz_id = 1,
                            Vreme_polaska_time = new TimeSpan(0, 7, 10, 0, 0)
                        },
                        new
                        {
                            Id = 40,
                            Aktivan = true,
                            Linija_id = 18,
                            Voz_id = 2,
                            Vreme_polaska_time = new TimeSpan(0, 15, 10, 0, 0)
                        },
                        new
                        {
                            Id = 41,
                            Aktivan = true,
                            Linija_id = 19,
                            Voz_id = 2,
                            Vreme_polaska_time = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 42,
                            Aktivan = true,
                            Linija_id = 19,
                            Voz_id = 1,
                            Vreme_polaska_time = new TimeSpan(0, 17, 0, 0, 0)
                        },
                        new
                        {
                            Id = 43,
                            Aktivan = true,
                            Linija_id = 20,
                            Voz_id = 1,
                            Vreme_polaska_time = new TimeSpan(0, 8, 30, 0, 0)
                        },
                        new
                        {
                            Id = 44,
                            Aktivan = true,
                            Linija_id = 20,
                            Voz_id = 2,
                            Vreme_polaska_time = new TimeSpan(0, 20, 30, 0, 0)
                        });
                });

            modelBuilder.Entity("ZelezniceSrbije.Models.Stanica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Stanica", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Naziv = "Beograd Centar",
                            Region = "Beograd"
                        },
                        new
                        {
                            Id = 2,
                            Naziv = "Novi Beograd",
                            Region = "Beograd"
                        },
                        new
                        {
                            Id = 3,
                            Naziv = "Zemun",
                            Region = "Beograd"
                        },
                        new
                        {
                            Id = 4,
                            Naziv = "Batajnica",
                            Region = "Beograd"
                        },
                        new
                        {
                            Id = 5,
                            Naziv = "Nova Pazova",
                            Region = "Srem"
                        },
                        new
                        {
                            Id = 6,
                            Naziv = "Stara Pazova",
                            Region = "Srem"
                        },
                        new
                        {
                            Id = 7,
                            Naziv = "Inđija",
                            Region = "Srem"
                        },
                        new
                        {
                            Id = 8,
                            Naziv = "Beška",
                            Region = "Srem"
                        },
                        new
                        {
                            Id = 9,
                            Naziv = "Sremski Karlovci",
                            Region = "Srem"
                        },
                        new
                        {
                            Id = 10,
                            Naziv = "Petrovaradin",
                            Region = "Bačka"
                        },
                        new
                        {
                            Id = 11,
                            Naziv = "Novi Sad",
                            Region = "Bačka"
                        },
                        new
                        {
                            Id = 12,
                            Naziv = "Zmajevo",
                            Region = "Bačka"
                        },
                        new
                        {
                            Id = 13,
                            Naziv = "Vrbas Nova",
                            Region = "Bačka"
                        },
                        new
                        {
                            Id = 14,
                            Naziv = "Lovćenac-Mali Iđoš",
                            Region = "Bačka"
                        },
                        new
                        {
                            Id = 15,
                            Naziv = "Bačka Topola",
                            Region = "Bačka"
                        },
                        new
                        {
                            Id = 16,
                            Naziv = "Žednik",
                            Region = "Bačka"
                        },
                        new
                        {
                            Id = 17,
                            Naziv = "Subotica",
                            Region = "Bačka"
                        },
                        new
                        {
                            Id = 18,
                            Naziv = "Pančevo",
                            Region = "Banat"
                        },
                        new
                        {
                            Id = 19,
                            Naziv = "Vršac",
                            Region = "Banat"
                        },
                        new
                        {
                            Id = 20,
                            Naziv = "Ruma",
                            Region = "Srem"
                        },
                        new
                        {
                            Id = 21,
                            Naziv = "Sremska Mitrovica",
                            Region = "Srem"
                        },
                        new
                        {
                            Id = 22,
                            Naziv = "Šid",
                            Region = "Srem"
                        },
                        new
                        {
                            Id = 23,
                            Naziv = "Lajkovac",
                            Region = "Mačva i Kolubara"
                        },
                        new
                        {
                            Id = 24,
                            Naziv = "Valjevo",
                            Region = "Mačva i Kolubara"
                        },
                        new
                        {
                            Id = 25,
                            Naziv = "Požega",
                            Region = "Zlatibor"
                        },
                        new
                        {
                            Id = 26,
                            Naziv = "Užice",
                            Region = "Zlatibor"
                        },
                        new
                        {
                            Id = 27,
                            Naziv = "Mladenovac",
                            Region = "Šumadija"
                        },
                        new
                        {
                            Id = 28,
                            Naziv = "Lapovo",
                            Region = "Šumadija"
                        },
                        new
                        {
                            Id = 29,
                            Naziv = "Jagodina",
                            Region = "Pomoravlje"
                        },
                        new
                        {
                            Id = 30,
                            Naziv = "Ćuprija",
                            Region = "Pomoravlje"
                        },
                        new
                        {
                            Id = 31,
                            Naziv = "Paraćin",
                            Region = "Pomoravlje"
                        },
                        new
                        {
                            Id = 32,
                            Naziv = "Aleksinac",
                            Region = "Južna Srbija"
                        },
                        new
                        {
                            Id = 33,
                            Naziv = "Niš",
                            Region = "Južna Srbija"
                        });
                });

            modelBuilder.Entity("ZelezniceSrbije.Models.StanicaLinija", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Linija_id")
                        .HasColumnType("int")
                        .HasColumnName("Linija_id");

                    b.Property<int>("Redosled")
                        .HasColumnType("int")
                        .HasColumnName("Redosled");

                    b.Property<int>("Stanica_id")
                        .HasColumnType("int")
                        .HasColumnName("Stanica_id");

                    b.Property<int>("Vreme_od_polaska")
                        .HasColumnType("int")
                        .HasColumnName("Vreme_od_polaska");

                    b.HasKey("Id");

                    b.HasIndex("Linija_id");

                    b.HasIndex("Stanica_id");

                    b.ToTable("StanicaLinija", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Linija_id = 1,
                            Redosled = 1,
                            Stanica_id = 1,
                            Vreme_od_polaska = 0
                        },
                        new
                        {
                            Id = 2,
                            Linija_id = 1,
                            Redosled = 2,
                            Stanica_id = 2,
                            Vreme_od_polaska = 5
                        },
                        new
                        {
                            Id = 3,
                            Linija_id = 1,
                            Redosled = 3,
                            Stanica_id = 3,
                            Vreme_od_polaska = 10
                        },
                        new
                        {
                            Id = 4,
                            Linija_id = 1,
                            Redosled = 4,
                            Stanica_id = 4,
                            Vreme_od_polaska = 18
                        },
                        new
                        {
                            Id = 5,
                            Linija_id = 1,
                            Redosled = 5,
                            Stanica_id = 5,
                            Vreme_od_polaska = 25
                        },
                        new
                        {
                            Id = 6,
                            Linija_id = 1,
                            Redosled = 6,
                            Stanica_id = 6,
                            Vreme_od_polaska = 30
                        },
                        new
                        {
                            Id = 7,
                            Linija_id = 1,
                            Redosled = 7,
                            Stanica_id = 7,
                            Vreme_od_polaska = 38
                        },
                        new
                        {
                            Id = 8,
                            Linija_id = 1,
                            Redosled = 8,
                            Stanica_id = 8,
                            Vreme_od_polaska = 45
                        },
                        new
                        {
                            Id = 9,
                            Linija_id = 1,
                            Redosled = 9,
                            Stanica_id = 9,
                            Vreme_od_polaska = 55
                        },
                        new
                        {
                            Id = 10,
                            Linija_id = 1,
                            Redosled = 10,
                            Stanica_id = 10,
                            Vreme_od_polaska = 62
                        },
                        new
                        {
                            Id = 11,
                            Linija_id = 1,
                            Redosled = 11,
                            Stanica_id = 11,
                            Vreme_od_polaska = 68
                        },
                        new
                        {
                            Id = 12,
                            Linija_id = 2,
                            Redosled = 1,
                            Stanica_id = 11,
                            Vreme_od_polaska = 0
                        },
                        new
                        {
                            Id = 13,
                            Linija_id = 2,
                            Redosled = 2,
                            Stanica_id = 10,
                            Vreme_od_polaska = 6
                        },
                        new
                        {
                            Id = 14,
                            Linija_id = 2,
                            Redosled = 3,
                            Stanica_id = 9,
                            Vreme_od_polaska = 13
                        },
                        new
                        {
                            Id = 15,
                            Linija_id = 2,
                            Redosled = 4,
                            Stanica_id = 8,
                            Vreme_od_polaska = 23
                        },
                        new
                        {
                            Id = 16,
                            Linija_id = 2,
                            Redosled = 5,
                            Stanica_id = 7,
                            Vreme_od_polaska = 30
                        },
                        new
                        {
                            Id = 17,
                            Linija_id = 2,
                            Redosled = 6,
                            Stanica_id = 6,
                            Vreme_od_polaska = 38
                        },
                        new
                        {
                            Id = 18,
                            Linija_id = 2,
                            Redosled = 7,
                            Stanica_id = 5,
                            Vreme_od_polaska = 43
                        },
                        new
                        {
                            Id = 19,
                            Linija_id = 2,
                            Redosled = 8,
                            Stanica_id = 4,
                            Vreme_od_polaska = 50
                        },
                        new
                        {
                            Id = 20,
                            Linija_id = 2,
                            Redosled = 9,
                            Stanica_id = 3,
                            Vreme_od_polaska = 58
                        },
                        new
                        {
                            Id = 21,
                            Linija_id = 2,
                            Redosled = 10,
                            Stanica_id = 2,
                            Vreme_od_polaska = 63
                        },
                        new
                        {
                            Id = 22,
                            Linija_id = 2,
                            Redosled = 11,
                            Stanica_id = 1,
                            Vreme_od_polaska = 68
                        },
                        new
                        {
                            Id = 23,
                            Linija_id = 3,
                            Redosled = 1,
                            Stanica_id = 17,
                            Vreme_od_polaska = 0
                        },
                        new
                        {
                            Id = 24,
                            Linija_id = 3,
                            Redosled = 2,
                            Stanica_id = 16,
                            Vreme_od_polaska = 10
                        },
                        new
                        {
                            Id = 25,
                            Linija_id = 3,
                            Redosled = 3,
                            Stanica_id = 15,
                            Vreme_od_polaska = 25
                        },
                        new
                        {
                            Id = 26,
                            Linija_id = 3,
                            Redosled = 4,
                            Stanica_id = 14,
                            Vreme_od_polaska = 35
                        },
                        new
                        {
                            Id = 27,
                            Linija_id = 3,
                            Redosled = 5,
                            Stanica_id = 13,
                            Vreme_od_polaska = 45
                        },
                        new
                        {
                            Id = 28,
                            Linija_id = 3,
                            Redosled = 6,
                            Stanica_id = 12,
                            Vreme_od_polaska = 55
                        },
                        new
                        {
                            Id = 29,
                            Linija_id = 3,
                            Redosled = 7,
                            Stanica_id = 11,
                            Vreme_od_polaska = 75
                        },
                        new
                        {
                            Id = 30,
                            Linija_id = 3,
                            Redosled = 8,
                            Stanica_id = 10,
                            Vreme_od_polaska = 81
                        },
                        new
                        {
                            Id = 31,
                            Linija_id = 3,
                            Redosled = 9,
                            Stanica_id = 9,
                            Vreme_od_polaska = 88
                        },
                        new
                        {
                            Id = 32,
                            Linija_id = 3,
                            Redosled = 10,
                            Stanica_id = 8,
                            Vreme_od_polaska = 98
                        },
                        new
                        {
                            Id = 33,
                            Linija_id = 3,
                            Redosled = 11,
                            Stanica_id = 7,
                            Vreme_od_polaska = 105
                        },
                        new
                        {
                            Id = 34,
                            Linija_id = 3,
                            Redosled = 12,
                            Stanica_id = 6,
                            Vreme_od_polaska = 113
                        },
                        new
                        {
                            Id = 35,
                            Linija_id = 3,
                            Redosled = 13,
                            Stanica_id = 5,
                            Vreme_od_polaska = 118
                        },
                        new
                        {
                            Id = 36,
                            Linija_id = 3,
                            Redosled = 14,
                            Stanica_id = 4,
                            Vreme_od_polaska = 125
                        },
                        new
                        {
                            Id = 37,
                            Linija_id = 3,
                            Redosled = 15,
                            Stanica_id = 3,
                            Vreme_od_polaska = 133
                        },
                        new
                        {
                            Id = 38,
                            Linija_id = 3,
                            Redosled = 16,
                            Stanica_id = 2,
                            Vreme_od_polaska = 138
                        },
                        new
                        {
                            Id = 39,
                            Linija_id = 3,
                            Redosled = 17,
                            Stanica_id = 1,
                            Vreme_od_polaska = 143
                        },
                        new
                        {
                            Id = 40,
                            Linija_id = 4,
                            Redosled = 1,
                            Stanica_id = 1,
                            Vreme_od_polaska = 0
                        },
                        new
                        {
                            Id = 41,
                            Linija_id = 4,
                            Redosled = 2,
                            Stanica_id = 2,
                            Vreme_od_polaska = 5
                        },
                        new
                        {
                            Id = 42,
                            Linija_id = 4,
                            Redosled = 3,
                            Stanica_id = 3,
                            Vreme_od_polaska = 10
                        },
                        new
                        {
                            Id = 43,
                            Linija_id = 4,
                            Redosled = 4,
                            Stanica_id = 4,
                            Vreme_od_polaska = 18
                        },
                        new
                        {
                            Id = 44,
                            Linija_id = 4,
                            Redosled = 5,
                            Stanica_id = 5,
                            Vreme_od_polaska = 25
                        },
                        new
                        {
                            Id = 45,
                            Linija_id = 4,
                            Redosled = 6,
                            Stanica_id = 6,
                            Vreme_od_polaska = 30
                        },
                        new
                        {
                            Id = 46,
                            Linija_id = 4,
                            Redosled = 7,
                            Stanica_id = 7,
                            Vreme_od_polaska = 38
                        },
                        new
                        {
                            Id = 47,
                            Linija_id = 4,
                            Redosled = 8,
                            Stanica_id = 8,
                            Vreme_od_polaska = 45
                        },
                        new
                        {
                            Id = 48,
                            Linija_id = 4,
                            Redosled = 9,
                            Stanica_id = 9,
                            Vreme_od_polaska = 55
                        },
                        new
                        {
                            Id = 49,
                            Linija_id = 4,
                            Redosled = 10,
                            Stanica_id = 10,
                            Vreme_od_polaska = 62
                        },
                        new
                        {
                            Id = 50,
                            Linija_id = 4,
                            Redosled = 11,
                            Stanica_id = 11,
                            Vreme_od_polaska = 68
                        },
                        new
                        {
                            Id = 51,
                            Linija_id = 4,
                            Redosled = 12,
                            Stanica_id = 12,
                            Vreme_od_polaska = 88
                        },
                        new
                        {
                            Id = 52,
                            Linija_id = 4,
                            Redosled = 13,
                            Stanica_id = 13,
                            Vreme_od_polaska = 98
                        },
                        new
                        {
                            Id = 53,
                            Linija_id = 4,
                            Redosled = 14,
                            Stanica_id = 14,
                            Vreme_od_polaska = 108
                        },
                        new
                        {
                            Id = 54,
                            Linija_id = 4,
                            Redosled = 15,
                            Stanica_id = 15,
                            Vreme_od_polaska = 118
                        },
                        new
                        {
                            Id = 55,
                            Linija_id = 4,
                            Redosled = 16,
                            Stanica_id = 16,
                            Vreme_od_polaska = 133
                        },
                        new
                        {
                            Id = 56,
                            Linija_id = 4,
                            Redosled = 17,
                            Stanica_id = 17,
                            Vreme_od_polaska = 143
                        },
                        new
                        {
                            Id = 57,
                            Linija_id = 5,
                            Redosled = 1,
                            Stanica_id = 17,
                            Vreme_od_polaska = 0
                        },
                        new
                        {
                            Id = 58,
                            Linija_id = 5,
                            Redosled = 2,
                            Stanica_id = 15,
                            Vreme_od_polaska = 20
                        },
                        new
                        {
                            Id = 59,
                            Linija_id = 5,
                            Redosled = 3,
                            Stanica_id = 13,
                            Vreme_od_polaska = 35
                        },
                        new
                        {
                            Id = 60,
                            Linija_id = 5,
                            Redosled = 4,
                            Stanica_id = 11,
                            Vreme_od_polaska = 60
                        },
                        new
                        {
                            Id = 61,
                            Linija_id = 5,
                            Redosled = 5,
                            Stanica_id = 1,
                            Vreme_od_polaska = 110
                        },
                        new
                        {
                            Id = 62,
                            Linija_id = 6,
                            Redosled = 1,
                            Stanica_id = 3,
                            Vreme_od_polaska = 0
                        },
                        new
                        {
                            Id = 63,
                            Linija_id = 6,
                            Redosled = 2,
                            Stanica_id = 2,
                            Vreme_od_polaska = 5
                        },
                        new
                        {
                            Id = 64,
                            Linija_id = 6,
                            Redosled = 3,
                            Stanica_id = 1,
                            Vreme_od_polaska = 10
                        },
                        new
                        {
                            Id = 65,
                            Linija_id = 6,
                            Redosled = 4,
                            Stanica_id = 27,
                            Vreme_od_polaska = 50
                        },
                        new
                        {
                            Id = 66,
                            Linija_id = 6,
                            Redosled = 5,
                            Stanica_id = 28,
                            Vreme_od_polaska = 80
                        },
                        new
                        {
                            Id = 67,
                            Linija_id = 6,
                            Redosled = 6,
                            Stanica_id = 29,
                            Vreme_od_polaska = 95
                        },
                        new
                        {
                            Id = 68,
                            Linija_id = 6,
                            Redosled = 7,
                            Stanica_id = 30,
                            Vreme_od_polaska = 105
                        },
                        new
                        {
                            Id = 69,
                            Linija_id = 6,
                            Redosled = 8,
                            Stanica_id = 31,
                            Vreme_od_polaska = 115
                        },
                        new
                        {
                            Id = 70,
                            Linija_id = 6,
                            Redosled = 9,
                            Stanica_id = 32,
                            Vreme_od_polaska = 135
                        },
                        new
                        {
                            Id = 71,
                            Linija_id = 6,
                            Redosled = 10,
                            Stanica_id = 33,
                            Vreme_od_polaska = 160
                        },
                        new
                        {
                            Id = 72,
                            Linija_id = 7,
                            Redosled = 1,
                            Stanica_id = 33,
                            Vreme_od_polaska = 0
                        },
                        new
                        {
                            Id = 73,
                            Linija_id = 7,
                            Redosled = 2,
                            Stanica_id = 32,
                            Vreme_od_polaska = 25
                        },
                        new
                        {
                            Id = 74,
                            Linija_id = 7,
                            Redosled = 3,
                            Stanica_id = 31,
                            Vreme_od_polaska = 45
                        },
                        new
                        {
                            Id = 75,
                            Linija_id = 7,
                            Redosled = 4,
                            Stanica_id = 30,
                            Vreme_od_polaska = 55
                        },
                        new
                        {
                            Id = 76,
                            Linija_id = 7,
                            Redosled = 5,
                            Stanica_id = 29,
                            Vreme_od_polaska = 65
                        },
                        new
                        {
                            Id = 77,
                            Linija_id = 7,
                            Redosled = 6,
                            Stanica_id = 28,
                            Vreme_od_polaska = 80
                        },
                        new
                        {
                            Id = 78,
                            Linija_id = 7,
                            Redosled = 7,
                            Stanica_id = 27,
                            Vreme_od_polaska = 110
                        },
                        new
                        {
                            Id = 79,
                            Linija_id = 7,
                            Redosled = 8,
                            Stanica_id = 1,
                            Vreme_od_polaska = 150
                        },
                        new
                        {
                            Id = 80,
                            Linija_id = 7,
                            Redosled = 9,
                            Stanica_id = 2,
                            Vreme_od_polaska = 155
                        },
                        new
                        {
                            Id = 81,
                            Linija_id = 7,
                            Redosled = 10,
                            Stanica_id = 3,
                            Vreme_od_polaska = 160
                        },
                        new
                        {
                            Id = 82,
                            Linija_id = 8,
                            Redosled = 1,
                            Stanica_id = 3,
                            Vreme_od_polaska = 0
                        },
                        new
                        {
                            Id = 83,
                            Linija_id = 8,
                            Redosled = 2,
                            Stanica_id = 2,
                            Vreme_od_polaska = 5
                        },
                        new
                        {
                            Id = 84,
                            Linija_id = 8,
                            Redosled = 3,
                            Stanica_id = 1,
                            Vreme_od_polaska = 10
                        },
                        new
                        {
                            Id = 85,
                            Linija_id = 8,
                            Redosled = 4,
                            Stanica_id = 18,
                            Vreme_od_polaska = 30
                        },
                        new
                        {
                            Id = 86,
                            Linija_id = 9,
                            Redosled = 1,
                            Stanica_id = 18,
                            Vreme_od_polaska = 0
                        },
                        new
                        {
                            Id = 87,
                            Linija_id = 9,
                            Redosled = 2,
                            Stanica_id = 1,
                            Vreme_od_polaska = 20
                        },
                        new
                        {
                            Id = 88,
                            Linija_id = 9,
                            Redosled = 3,
                            Stanica_id = 2,
                            Vreme_od_polaska = 25
                        },
                        new
                        {
                            Id = 89,
                            Linija_id = 9,
                            Redosled = 4,
                            Stanica_id = 3,
                            Vreme_od_polaska = 30
                        },
                        new
                        {
                            Id = 90,
                            Linija_id = 10,
                            Redosled = 1,
                            Stanica_id = 3,
                            Vreme_od_polaska = 0
                        },
                        new
                        {
                            Id = 91,
                            Linija_id = 10,
                            Redosled = 2,
                            Stanica_id = 2,
                            Vreme_od_polaska = 5
                        },
                        new
                        {
                            Id = 92,
                            Linija_id = 10,
                            Redosled = 3,
                            Stanica_id = 1,
                            Vreme_od_polaska = 10
                        },
                        new
                        {
                            Id = 93,
                            Linija_id = 10,
                            Redosled = 4,
                            Stanica_id = 18,
                            Vreme_od_polaska = 30
                        },
                        new
                        {
                            Id = 94,
                            Linija_id = 10,
                            Redosled = 5,
                            Stanica_id = 19,
                            Vreme_od_polaska = 75
                        },
                        new
                        {
                            Id = 95,
                            Linija_id = 11,
                            Redosled = 1,
                            Stanica_id = 19,
                            Vreme_od_polaska = 0
                        },
                        new
                        {
                            Id = 96,
                            Linija_id = 11,
                            Redosled = 2,
                            Stanica_id = 18,
                            Vreme_od_polaska = 45
                        },
                        new
                        {
                            Id = 97,
                            Linija_id = 11,
                            Redosled = 3,
                            Stanica_id = 1,
                            Vreme_od_polaska = 65
                        },
                        new
                        {
                            Id = 98,
                            Linija_id = 11,
                            Redosled = 4,
                            Stanica_id = 2,
                            Vreme_od_polaska = 70
                        },
                        new
                        {
                            Id = 99,
                            Linija_id = 11,
                            Redosled = 5,
                            Stanica_id = 3,
                            Vreme_od_polaska = 75
                        },
                        new
                        {
                            Id = 100,
                            Linija_id = 12,
                            Redosled = 1,
                            Stanica_id = 3,
                            Vreme_od_polaska = 0
                        },
                        new
                        {
                            Id = 101,
                            Linija_id = 12,
                            Redosled = 2,
                            Stanica_id = 4,
                            Vreme_od_polaska = 8
                        },
                        new
                        {
                            Id = 102,
                            Linija_id = 12,
                            Redosled = 3,
                            Stanica_id = 5,
                            Vreme_od_polaska = 15
                        },
                        new
                        {
                            Id = 103,
                            Linija_id = 12,
                            Redosled = 4,
                            Stanica_id = 6,
                            Vreme_od_polaska = 20
                        },
                        new
                        {
                            Id = 104,
                            Linija_id = 12,
                            Redosled = 5,
                            Stanica_id = 20,
                            Vreme_od_polaska = 45
                        },
                        new
                        {
                            Id = 105,
                            Linija_id = 12,
                            Redosled = 6,
                            Stanica_id = 21,
                            Vreme_od_polaska = 60
                        },
                        new
                        {
                            Id = 106,
                            Linija_id = 12,
                            Redosled = 7,
                            Stanica_id = 22,
                            Vreme_od_polaska = 80
                        },
                        new
                        {
                            Id = 107,
                            Linija_id = 13,
                            Redosled = 1,
                            Stanica_id = 22,
                            Vreme_od_polaska = 0
                        },
                        new
                        {
                            Id = 108,
                            Linija_id = 13,
                            Redosled = 2,
                            Stanica_id = 21,
                            Vreme_od_polaska = 20
                        },
                        new
                        {
                            Id = 109,
                            Linija_id = 13,
                            Redosled = 3,
                            Stanica_id = 20,
                            Vreme_od_polaska = 35
                        },
                        new
                        {
                            Id = 110,
                            Linija_id = 13,
                            Redosled = 4,
                            Stanica_id = 6,
                            Vreme_od_polaska = 60
                        },
                        new
                        {
                            Id = 111,
                            Linija_id = 13,
                            Redosled = 5,
                            Stanica_id = 5,
                            Vreme_od_polaska = 65
                        },
                        new
                        {
                            Id = 112,
                            Linija_id = 13,
                            Redosled = 6,
                            Stanica_id = 4,
                            Vreme_od_polaska = 72
                        },
                        new
                        {
                            Id = 113,
                            Linija_id = 13,
                            Redosled = 7,
                            Stanica_id = 3,
                            Vreme_od_polaska = 80
                        },
                        new
                        {
                            Id = 114,
                            Linija_id = 14,
                            Redosled = 1,
                            Stanica_id = 11,
                            Vreme_od_polaska = 0
                        },
                        new
                        {
                            Id = 115,
                            Linija_id = 14,
                            Redosled = 2,
                            Stanica_id = 10,
                            Vreme_od_polaska = 6
                        },
                        new
                        {
                            Id = 116,
                            Linija_id = 14,
                            Redosled = 3,
                            Stanica_id = 9,
                            Vreme_od_polaska = 13
                        },
                        new
                        {
                            Id = 117,
                            Linija_id = 14,
                            Redosled = 4,
                            Stanica_id = 8,
                            Vreme_od_polaska = 23
                        },
                        new
                        {
                            Id = 118,
                            Linija_id = 14,
                            Redosled = 5,
                            Stanica_id = 7,
                            Vreme_od_polaska = 30
                        },
                        new
                        {
                            Id = 119,
                            Linija_id = 14,
                            Redosled = 6,
                            Stanica_id = 6,
                            Vreme_od_polaska = 38
                        },
                        new
                        {
                            Id = 120,
                            Linija_id = 14,
                            Redosled = 7,
                            Stanica_id = 20,
                            Vreme_od_polaska = 63
                        },
                        new
                        {
                            Id = 121,
                            Linija_id = 14,
                            Redosled = 8,
                            Stanica_id = 21,
                            Vreme_od_polaska = 78
                        },
                        new
                        {
                            Id = 122,
                            Linija_id = 14,
                            Redosled = 9,
                            Stanica_id = 22,
                            Vreme_od_polaska = 98
                        },
                        new
                        {
                            Id = 123,
                            Linija_id = 15,
                            Redosled = 1,
                            Stanica_id = 22,
                            Vreme_od_polaska = 0
                        },
                        new
                        {
                            Id = 124,
                            Linija_id = 15,
                            Redosled = 2,
                            Stanica_id = 21,
                            Vreme_od_polaska = 20
                        },
                        new
                        {
                            Id = 125,
                            Linija_id = 15,
                            Redosled = 3,
                            Stanica_id = 20,
                            Vreme_od_polaska = 35
                        },
                        new
                        {
                            Id = 126,
                            Linija_id = 15,
                            Redosled = 4,
                            Stanica_id = 6,
                            Vreme_od_polaska = 60
                        },
                        new
                        {
                            Id = 127,
                            Linija_id = 15,
                            Redosled = 5,
                            Stanica_id = 7,
                            Vreme_od_polaska = 68
                        },
                        new
                        {
                            Id = 128,
                            Linija_id = 15,
                            Redosled = 6,
                            Stanica_id = 8,
                            Vreme_od_polaska = 75
                        },
                        new
                        {
                            Id = 129,
                            Linija_id = 15,
                            Redosled = 7,
                            Stanica_id = 9,
                            Vreme_od_polaska = 85
                        },
                        new
                        {
                            Id = 130,
                            Linija_id = 15,
                            Redosled = 8,
                            Stanica_id = 10,
                            Vreme_od_polaska = 92
                        },
                        new
                        {
                            Id = 131,
                            Linija_id = 15,
                            Redosled = 9,
                            Stanica_id = 11,
                            Vreme_od_polaska = 98
                        },
                        new
                        {
                            Id = 132,
                            Linija_id = 16,
                            Redosled = 1,
                            Stanica_id = 3,
                            Vreme_od_polaska = 0
                        },
                        new
                        {
                            Id = 133,
                            Linija_id = 16,
                            Redosled = 2,
                            Stanica_id = 2,
                            Vreme_od_polaska = 5
                        },
                        new
                        {
                            Id = 134,
                            Linija_id = 16,
                            Redosled = 3,
                            Stanica_id = 1,
                            Vreme_od_polaska = 10
                        },
                        new
                        {
                            Id = 135,
                            Linija_id = 16,
                            Redosled = 4,
                            Stanica_id = 23,
                            Vreme_od_polaska = 60
                        },
                        new
                        {
                            Id = 136,
                            Linija_id = 16,
                            Redosled = 5,
                            Stanica_id = 24,
                            Vreme_od_polaska = 80
                        },
                        new
                        {
                            Id = 137,
                            Linija_id = 16,
                            Redosled = 6,
                            Stanica_id = 25,
                            Vreme_od_polaska = 130
                        },
                        new
                        {
                            Id = 138,
                            Linija_id = 16,
                            Redosled = 7,
                            Stanica_id = 26,
                            Vreme_od_polaska = 150
                        },
                        new
                        {
                            Id = 139,
                            Linija_id = 17,
                            Redosled = 1,
                            Stanica_id = 26,
                            Vreme_od_polaska = 0
                        },
                        new
                        {
                            Id = 140,
                            Linija_id = 17,
                            Redosled = 2,
                            Stanica_id = 25,
                            Vreme_od_polaska = 20
                        },
                        new
                        {
                            Id = 141,
                            Linija_id = 17,
                            Redosled = 3,
                            Stanica_id = 24,
                            Vreme_od_polaska = 70
                        },
                        new
                        {
                            Id = 142,
                            Linija_id = 17,
                            Redosled = 4,
                            Stanica_id = 23,
                            Vreme_od_polaska = 90
                        },
                        new
                        {
                            Id = 143,
                            Linija_id = 17,
                            Redosled = 5,
                            Stanica_id = 1,
                            Vreme_od_polaska = 140
                        },
                        new
                        {
                            Id = 144,
                            Linija_id = 17,
                            Redosled = 6,
                            Stanica_id = 2,
                            Vreme_od_polaska = 145
                        },
                        new
                        {
                            Id = 145,
                            Linija_id = 17,
                            Redosled = 7,
                            Stanica_id = 3,
                            Vreme_od_polaska = 150
                        },
                        new
                        {
                            Id = 146,
                            Linija_id = 18,
                            Redosled = 1,
                            Stanica_id = 3,
                            Vreme_od_polaska = 0
                        },
                        new
                        {
                            Id = 147,
                            Linija_id = 18,
                            Redosled = 2,
                            Stanica_id = 2,
                            Vreme_od_polaska = 5
                        },
                        new
                        {
                            Id = 148,
                            Linija_id = 18,
                            Redosled = 3,
                            Stanica_id = 1,
                            Vreme_od_polaska = 10
                        },
                        new
                        {
                            Id = 149,
                            Linija_id = 18,
                            Redosled = 4,
                            Stanica_id = 23,
                            Vreme_od_polaska = 60
                        },
                        new
                        {
                            Id = 150,
                            Linija_id = 18,
                            Redosled = 5,
                            Stanica_id = 24,
                            Vreme_od_polaska = 80
                        },
                        new
                        {
                            Id = 151,
                            Linija_id = 19,
                            Redosled = 1,
                            Stanica_id = 24,
                            Vreme_od_polaska = 0
                        },
                        new
                        {
                            Id = 152,
                            Linija_id = 19,
                            Redosled = 2,
                            Stanica_id = 23,
                            Vreme_od_polaska = 20
                        },
                        new
                        {
                            Id = 153,
                            Linija_id = 19,
                            Redosled = 3,
                            Stanica_id = 1,
                            Vreme_od_polaska = 70
                        },
                        new
                        {
                            Id = 154,
                            Linija_id = 19,
                            Redosled = 4,
                            Stanica_id = 2,
                            Vreme_od_polaska = 75
                        },
                        new
                        {
                            Id = 155,
                            Linija_id = 19,
                            Redosled = 5,
                            Stanica_id = 3,
                            Vreme_od_polaska = 80
                        },
                        new
                        {
                            Id = 156,
                            Linija_id = 20,
                            Redosled = 1,
                            Stanica_id = 1,
                            Vreme_od_polaska = 0
                        },
                        new
                        {
                            Id = 157,
                            Linija_id = 20,
                            Redosled = 2,
                            Stanica_id = 18,
                            Vreme_od_polaska = 20
                        },
                        new
                        {
                            Id = 158,
                            Linija_id = 20,
                            Redosled = 3,
                            Stanica_id = 19,
                            Vreme_od_polaska = 65
                        });
                });

            modelBuilder.Entity("ZelezniceSrbije.Models.TipVoza", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("TipVoza", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Naziv = "Soko",
                            Opis = "Najbrzi vozicc"
                        },
                        new
                        {
                            Id = 2,
                            Naziv = "InterCity",
                            Opis = "Brzi međugradski voz"
                        },
                        new
                        {
                            Id = 3,
                            Naziv = "Regio Express",
                            Opis = "Polubrzi voz između malo većih mesta"
                        },
                        new
                        {
                            Id = 4,
                            Naziv = "Regio",
                            Opis = "Regionalni voz. Staje na svaku banderu"
                        });
                });

            modelBuilder.Entity("ZelezniceSrbije.Models.Voz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktivan")
                        .HasColumnType("bit");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Serijski_broj")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Tip_voza_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Tip_voza_id");

                    b.ToTable("Voz", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aktivan = true,
                            Naziv = "Stadler KISS 200",
                            Serijski_broj = "KISS-200-01",
                            Tip_voza_id = 1
                        },
                        new
                        {
                            Id = 2,
                            Aktivan = true,
                            Naziv = "Stadler KISS 200-2",
                            Serijski_broj = "KISS-200-02",
                            Tip_voza_id = 2
                        },
                        new
                        {
                            Id = 3,
                            Aktivan = true,
                            Naziv = "Stadler FLIRT 3",
                            Serijski_broj = "FLIRT-3-01",
                            Tip_voza_id = 3
                        },
                        new
                        {
                            Id = 4,
                            Aktivan = true,
                            Naziv = "Siemens Desiro",
                            Serijski_broj = "DESIRO-012",
                            Tip_voza_id = 4
                        });
                });

            modelBuilder.Entity("ZelezniceSrbije.Models.Administrator", b =>
                {
                    b.HasBaseType("ZelezniceSrbije.Models.Korisnik");

                    b.Property<DateTime>("Datum_zaposlenja")
                        .HasColumnType("datetime2")
                        .HasColumnName("datum_zaposlenja");

                    b.ToTable("Administrator", (string)null);
                });

            modelBuilder.Entity("ZelezniceSrbije.Models.Kondukter", b =>
                {
                    b.HasBaseType("ZelezniceSrbije.Models.Korisnik");

                    b.Property<string>("Broj_legitimacije")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("broj_legitimacije");

                    b.ToTable("Kondukter", (string)null);
                });

            modelBuilder.Entity("ZelezniceSrbije.Models.Putnik", b =>
                {
                    b.HasBaseType("ZelezniceSrbije.Models.Korisnik");

                    b.Property<string>("Broj_telefona")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("broj_telefona");

                    b.ToTable("Putnik", (string)null);
                });

            modelBuilder.Entity("Raspored", b =>
                {
                    b.HasOne("ZelezniceSrbije.Models.Linija", "Linija")
                        .WithMany()
                        .HasForeignKey("Linija_id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ZelezniceSrbije.Models.RasporedSablon", null)
                        .WithMany()
                        .HasForeignKey("Sablon_id")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ZelezniceSrbije.Models.Voz", "Voz")
                        .WithMany()
                        .HasForeignKey("Voz_id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Linija");

                    b.Navigation("Voz");
                });

            modelBuilder.Entity("ZelezniceSrbije.Models.Karta", b =>
                {
                    b.HasOne("ZelezniceSrbije.Models.Korisnik", null)
                        .WithMany()
                        .HasForeignKey("Putnik_id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Raspored", null)
                        .WithMany()
                        .HasForeignKey("Raspored_id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("ZelezniceSrbije.Models.RasporedSablon", b =>
                {
                    b.HasOne("ZelezniceSrbije.Models.Linija", null)
                        .WithMany()
                        .HasForeignKey("Linija_id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ZelezniceSrbije.Models.Voz", null)
                        .WithMany()
                        .HasForeignKey("Voz_id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("ZelezniceSrbije.Models.StanicaLinija", b =>
                {
                    b.HasOne("ZelezniceSrbije.Models.Linija", "Linija")
                        .WithMany()
                        .HasForeignKey("Linija_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZelezniceSrbije.Models.Stanica", "Stanica")
                        .WithMany()
                        .HasForeignKey("Stanica_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Linija");

                    b.Navigation("Stanica");
                });

            modelBuilder.Entity("ZelezniceSrbije.Models.Voz", b =>
                {
                    b.HasOne("ZelezniceSrbije.Models.TipVoza", "TipVoza")
                        .WithMany()
                        .HasForeignKey("Tip_voza_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipVoza");
                });

            modelBuilder.Entity("ZelezniceSrbije.Models.Administrator", b =>
                {
                    b.HasOne("ZelezniceSrbije.Models.Korisnik", null)
                        .WithOne()
                        .HasForeignKey("ZelezniceSrbije.Models.Administrator", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ZelezniceSrbije.Models.Kondukter", b =>
                {
                    b.HasOne("ZelezniceSrbije.Models.Korisnik", null)
                        .WithOne()
                        .HasForeignKey("ZelezniceSrbije.Models.Kondukter", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ZelezniceSrbije.Models.Putnik", b =>
                {
                    b.HasOne("ZelezniceSrbije.Models.Korisnik", null)
                        .WithOne()
                        .HasForeignKey("ZelezniceSrbije.Models.Putnik", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
