USE [ZelezniceSrbije];
GO

INSERT INTO ZelezniceSrbije.dbo.Stanica (naziv, region) VALUES (N'Beograd Centar', N'Beograd');
INSERT INTO ZelezniceSrbije.dbo.Stanica (naziv, region) VALUES (N'Novi Beograd', N'Beograd');
INSERT INTO ZelezniceSrbije.dbo.Stanica (naziv, region) VALUES (N'Zemun', N'Beograd');
INSERT INTO ZelezniceSrbije.dbo.Stanica (naziv, region) VALUES (N'Batajnica', N'Beograd');
INSERT INTO ZelezniceSrbije.dbo.Stanica (naziv, region) VALUES (N'Nova Pazova', N'Srem');
INSERT INTO ZelezniceSrbije.dbo.Stanica (naziv, region) VALUES (N'Stara Pazova', N'Srem');
INSERT INTO ZelezniceSrbije.dbo.Stanica (naziv, region) VALUES (N'Inđija', N'Srem');
INSERT INTO ZelezniceSrbije.dbo.Stanica (naziv, region) VALUES (N'Beška', N'Srem');
INSERT INTO ZelezniceSrbije.dbo.Stanica (naziv, region) VALUES (N'Sremski Karlovci', N'Srem');
INSERT INTO ZelezniceSrbije.dbo.Stanica (naziv, region) VALUES (N'Petrovaradin', N'Bačka');
INSERT INTO ZelezniceSrbije.dbo.Stanica (naziv, region) VALUES (N'Novi Sad', N'Bačka');
INSERT INTO ZelezniceSrbije.dbo.Stanica (naziv, region) VALUES (N'Zmajevo', N'Bačka');
INSERT INTO ZelezniceSrbije.dbo.Stanica (naziv, region) VALUES (N'Vrbas Nova', N'Bačka');
INSERT INTO ZelezniceSrbije.dbo.Stanica (naziv, region) VALUES (N'Lovćenac-Mali Iđoš', N'Bačka');
INSERT INTO ZelezniceSrbije.dbo.Stanica (naziv, region) VALUES (N'Bačka Topola', N'Bačka');
INSERT INTO ZelezniceSrbije.dbo.Stanica (naziv, region) VALUES (N'Žednik', N'Bačka');
INSERT INTO ZelezniceSrbije.dbo.Stanica (naziv, region) VALUES (N'Subotica', N'Bačka');
INSERT INTO ZelezniceSrbije.dbo.Stanica (naziv, region) VALUES (N'Pančevo', N'Banat');
INSERT INTO ZelezniceSrbije.dbo.Stanica (naziv, region) VALUES (N'Vršac', N'Banat');
INSERT INTO ZelezniceSrbije.dbo.Stanica (naziv, region) VALUES (N'Ruma', N'Srem');
INSERT INTO ZelezniceSrbije.dbo.Stanica (naziv, region) VALUES (N'Sremska Mitrovica', N'Srem');
INSERT INTO ZelezniceSrbije.dbo.Stanica (naziv, region) VALUES (N'Šid', N'Srem');
INSERT INTO ZelezniceSrbije.dbo.Stanica (naziv, region) VALUES (N'Lajkovac', N'Mačva i Kolubara');
INSERT INTO ZelezniceSrbije.dbo.Stanica (naziv, region) VALUES (N'Valjevo', N'Mačva i Kolubara');
INSERT INTO ZelezniceSrbije.dbo.Stanica (naziv, region) VALUES (N'Požega', N'Zlatibor');
INSERT INTO ZelezniceSrbije.dbo.Stanica (naziv, region) VALUES (N'Užice', N'Zlatibor');
INSERT INTO ZelezniceSrbije.dbo.Stanica (naziv, region) VALUES (N'Mladenovac', N'Šumadija');
INSERT INTO ZelezniceSrbije.dbo.Stanica (naziv, region) VALUES (N'Lapovo', N'Šumadija');
INSERT INTO ZelezniceSrbije.dbo.Stanica (naziv, region) VALUES (N'Jagodina', N'Pomoravlje');
INSERT INTO ZelezniceSrbije.dbo.Stanica (naziv, region) VALUES (N'Ćuprija', N'Pomoravlje');
INSERT INTO ZelezniceSrbije.dbo.Stanica (naziv, region) VALUES (N'Paraćin', N'Pomoravlje');
INSERT INTO ZelezniceSrbije.dbo.Stanica (naziv, region) VALUES (N'Aleksinac', N'Južna Srbija');
INSERT INTO ZelezniceSrbije.dbo.Stanica (naziv, region) VALUES (N'Niš', N'Južna Srbija');
GO

INSERT INTO ZelezniceSrbije.dbo.Linija (naziv, cena_po_minutu) VALUES (N'Beograd Centar – Novi Sad', 12);
INSERT INTO ZelezniceSrbije.dbo.Linija (naziv, cena_po_minutu) VALUES (N'Novi Sad – Beograd Centar', 12);
INSERT INTO ZelezniceSrbije.dbo.Linija (naziv, cena_po_minutu) VALUES (N'Subotica – Beograd Centar', 18);
INSERT INTO ZelezniceSrbije.dbo.Linija (naziv, cena_po_minutu) VALUES (N'Beograd Centar – Subotica', 16);
INSERT INTO ZelezniceSrbije.dbo.Linija (naziv, cena_po_minutu) VALUES (N'Subotica – Beograd Centar', 16);
INSERT INTO ZelezniceSrbije.dbo.Linija (naziv, cena_po_minutu) VALUES (N'Zemun – Niš', 8);
INSERT INTO ZelezniceSrbije.dbo.Linija (naziv, cena_po_minutu) VALUES (N'Niš – Zemun', 8);
INSERT INTO ZelezniceSrbije.dbo.Linija (naziv, cena_po_minutu) VALUES (N'Zemun – Pančevo', 8);
INSERT INTO ZelezniceSrbije.dbo.Linija (naziv, cena_po_minutu) VALUES (N'Pančevo – Zemun', 8);
INSERT INTO ZelezniceSrbije.dbo.Linija (naziv, cena_po_minutu) VALUES (N'Zemun – Vršac', 8);
INSERT INTO ZelezniceSrbije.dbo.Linija (naziv, cena_po_minutu) VALUES (N'Vršac – Zemun', 8);
INSERT INTO ZelezniceSrbije.dbo.Linija (naziv, cena_po_minutu) VALUES (N'Zemun – Šid', 8);
INSERT INTO ZelezniceSrbije.dbo.Linija (naziv, cena_po_minutu) VALUES (N'Šid – Zemun', 8);
INSERT INTO ZelezniceSrbije.dbo.Linija (naziv, cena_po_minutu) VALUES (N'Novi Sad – Šid', 8);
INSERT INTO ZelezniceSrbije.dbo.Linija (naziv, cena_po_minutu) VALUES (N'Šid – Novi Sad', 8);
INSERT INTO ZelezniceSrbije.dbo.Linija (naziv, cena_po_minutu) VALUES (N'Zemun – Užice', 8);
INSERT INTO ZelezniceSrbije.dbo.Linija (naziv, cena_po_minutu) VALUES (N'Užice – Zemun', 8);
INSERT INTO ZelezniceSrbije.dbo.Linija (naziv, cena_po_minutu) VALUES (N'Zemun – Valjevo', 8);
INSERT INTO ZelezniceSrbije.dbo.Linija (naziv, cena_po_minutu) VALUES (N'Valjevo – Zemun', 8);
INSERT INTO ZelezniceSrbije.dbo.Linija (naziv, cena_po_minutu) VALUES (N'Beograd Centar - Vršac', 12);
GO

INSERT INTO ZelezniceSrbije.dbo.TipVoza (naziv, opis) VALUES (N'Soko', N'Najbrzi vozicc');
INSERT INTO ZelezniceSrbije.dbo.TipVoza (naziv, opis) VALUES (N'InterCity', N'Brzi međugradski voz');
INSERT INTO ZelezniceSrbije.dbo.TipVoza (naziv, opis) VALUES (N'Regio Express', N'Polubrzi voz između malo većih mesta');
INSERT INTO ZelezniceSrbije.dbo.TipVoza (naziv, opis) VALUES (N'Regio', N'Regionalni voz. Staje na svaku banderu');
GO

INSERT INTO ZelezniceSrbije.dbo.Voz (naziv, serijski_broj, aktivan, tip_voza_id) VALUES (N'Stadler KISS 200', N'KISS-200-01', 1, 1);
INSERT INTO ZelezniceSrbije.dbo.Voz (naziv, serijski_broj, aktivan, tip_voza_id) VALUES (N'Stadler KISS 200-2', N'KISS-200-02', 1, 2);
INSERT INTO ZelezniceSrbije.dbo.Voz (naziv, serijski_broj, aktivan, tip_voza_id) VALUES (N'Stadler FLIRT 3', N'FLIRT-3-01', 1, 3);
INSERT INTO ZelezniceSrbije.dbo.Voz (naziv, serijski_broj, aktivan, tip_voza_id) VALUES (N'Siemens Desiro', N'DESIRO-012', 1, 4);
GO

INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (0, 1, 1, 1);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (5, 2, 2, 1);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (10, 3, 3, 1);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (18, 4, 4, 1);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (25, 5, 5, 1);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (30, 6, 6, 1);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (38, 7, 7, 1);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (45, 8, 8, 1);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (55, 9, 9, 1);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (62, 10, 10, 1);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (68, 11, 11, 1);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (0, 1, 11, 2);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (6, 2, 10, 2);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (13, 3, 9, 2);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (23, 4, 8, 2);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (30, 5, 7, 2);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (38, 6, 6, 2);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (43, 7, 5, 2);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (50, 8, 4, 2);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (58, 9, 3, 2);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (63, 10, 2, 2);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (68, 11, 1, 2);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (0, 1, 17, 3);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (10, 2, 16, 3);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (25, 3, 15, 3);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (35, 4, 14, 3);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (45, 5, 13, 3);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (55, 6, 12, 3);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (75, 7, 11, 3);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (81, 8, 10, 3);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (88, 9, 9, 3);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (98, 10, 8, 3);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (105, 11, 7, 3);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (113, 12, 6, 3);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (118, 13, 5, 3);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (125, 14, 4, 3);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (133, 15, 3, 3);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (138, 16, 2, 3);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (143, 17, 1, 3);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (0, 1, 1, 4);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (5, 2, 2, 4);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (10, 3, 3, 4);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (18, 4, 4, 4);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (25, 5, 5, 4);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (30, 6, 6, 4);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (38, 7, 7, 4);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (45, 8, 8, 4);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (55, 9, 9, 4);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (62, 10, 10, 4);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (68, 11, 11, 4);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (88, 12, 12, 4);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (98, 13, 13, 4);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (108, 14, 14, 4);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (118, 15, 15, 4);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (133, 16, 16, 4);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (143, 17, 17, 4);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (0, 1, 17, 5);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (20, 2, 15, 5);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (35, 3, 13, 5);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (60, 4, 11, 5);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (110, 5, 1, 5);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (0, 1, 3, 6);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (5, 2, 2, 6);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (10, 3, 1, 6);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (50, 4, 27, 6);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (80, 5, 28, 6);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (95, 6, 29, 6);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (105, 7, 30, 6);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (115, 8, 31, 6);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (135, 9, 32, 6);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (160, 10, 33, 6);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (0, 1, 33, 7);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (25, 2, 32, 7);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (45, 3, 31, 7);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (55, 4, 30, 7);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (65, 5, 29, 7);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (80, 6, 28, 7);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (110, 7, 27, 7);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (150, 8, 1, 7);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (155, 9, 2, 7);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (160, 10, 3, 7);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (0, 1, 3, 8);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (5, 2, 2, 8);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (10, 3, 1, 8);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (30, 4, 18, 8);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (0, 1, 18, 9);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (20, 2, 1, 9);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (25, 3, 2, 9);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (30, 4, 3, 9);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (0, 1, 3, 10);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (5, 2, 2, 10);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (10, 3, 1, 10);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (30, 4, 18, 10);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (75, 5, 19, 10);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (0, 1, 19, 11);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (45, 2, 18, 11);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (65, 3, 1, 11);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (70, 4, 2, 11);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (75, 5, 3, 11);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (0, 1, 3, 12);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (8, 2, 4, 12);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (15, 3, 5, 12);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (20, 4, 6, 12);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (45, 5, 20, 12);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (60, 6, 21, 12);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (80, 7, 22, 12);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (0, 1, 22, 13);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (20, 2, 21, 13);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (35, 3, 20, 13);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (60, 4, 6, 13);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (65, 5, 5, 13);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (72, 6, 4, 13);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (80, 7, 3, 13);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (0, 1, 11, 14);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (6, 2, 10, 14);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (13, 3, 9, 14);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (23, 4, 8, 14);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (30, 5, 7, 14);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (38, 6, 6, 14);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (63, 7, 20, 14);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (78, 8, 21, 14);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (98, 9, 22, 14);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (0, 1, 22, 15);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (20, 2, 21, 15);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (35, 3, 20, 15);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (60, 4, 6, 15);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (68, 5, 7, 15);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (75, 6, 8, 15);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (85, 7, 9, 15);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (92, 8, 10, 15);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (98, 9, 11, 15);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (0, 1, 3, 16);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (5, 2, 2, 16);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (10, 3, 1, 16);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (60, 4, 23, 16);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (80, 5, 24, 16);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (130, 6, 25, 16);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (150, 7, 26, 16);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (0, 1, 26, 17);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (20, 2, 25, 17);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (70, 3, 24, 17);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (90, 4, 23, 17);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (140, 5, 1, 17);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (145, 6, 2, 17);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (150, 7, 3, 17);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (0, 1, 3, 18);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (5, 2, 2, 18);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (10, 3, 1, 18);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (60, 4, 23, 18);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (80, 5, 24, 18);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (0, 1, 24, 19);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (20, 2, 23, 19);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (70, 3, 1, 19);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (75, 4, 2, 19);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (80, 5, 3, 19);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (0, 1, 1, 20);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (20, 2, 18, 20);
INSERT INTO ZelezniceSrbije.dbo.StanicaLinija (vreme_od_polaska, redosled, stanica_id, linija_id) VALUES (65, 3, 19, 20);
GO

INSERT INTO ZelezniceSrbije.dbo.RasporedSablon (linija_id, voz_id, vreme_polaska_time, aktivan) VALUES (1, 1, N'07:00:00', 1);
INSERT INTO ZelezniceSrbije.dbo.RasporedSablon (linija_id, voz_id, vreme_polaska_time, aktivan) VALUES (1, 2, N'13:00:00', 1);
INSERT INTO ZelezniceSrbije.dbo.RasporedSablon (linija_id, voz_id, vreme_polaska_time, aktivan) VALUES (1, 1, N'19:00:00', 1);
INSERT INTO ZelezniceSrbije.dbo.RasporedSablon (linija_id, voz_id, vreme_polaska_time, aktivan) VALUES (2, 2, N'09:00:00', 1);
INSERT INTO ZelezniceSrbije.dbo.RasporedSablon (linija_id, voz_id, vreme_polaska_time, aktivan) VALUES (2, 1, N'15:00:00', 1);
INSERT INTO ZelezniceSrbije.dbo.RasporedSablon (linija_id, voz_id, vreme_polaska_time, aktivan) VALUES (2, 2, N'21:00:00', 1);
INSERT INTO ZelezniceSrbije.dbo.RasporedSablon (linija_id, voz_id, vreme_polaska_time, aktivan) VALUES (3, 1, N'06:00:00', 1);
INSERT INTO ZelezniceSrbije.dbo.RasporedSablon (linija_id, voz_id, vreme_polaska_time, aktivan) VALUES (3, 2, N'14:00:00', 1);
INSERT INTO ZelezniceSrbije.dbo.RasporedSablon (linija_id, voz_id, vreme_polaska_time, aktivan) VALUES (4, 2, N'09:30:00', 1);
INSERT INTO ZelezniceSrbije.dbo.RasporedSablon (linija_id, voz_id, vreme_polaska_time, aktivan) VALUES (4, 1, N'17:30:00', 1);
INSERT INTO ZelezniceSrbije.dbo.RasporedSablon (linija_id, voz_id, vreme_polaska_time, aktivan) VALUES (5, 1, N'07:15:00', 1);
INSERT INTO ZelezniceSrbije.dbo.RasporedSablon (linija_id, voz_id, vreme_polaska_time, aktivan) VALUES (5, 2, N'16:15:00', 1);
INSERT INTO ZelezniceSrbije.dbo.RasporedSablon (linija_id, voz_id, vreme_polaska_time, aktivan) VALUES (6, 1, N'05:00:00', 1);
INSERT INTO ZelezniceSrbije.dbo.RasporedSablon (linija_id, voz_id, vreme_polaska_time, aktivan) VALUES (6, 2, N'15:00:00', 1);
INSERT INTO ZelezniceSrbije.dbo.RasporedSablon (linija_id, voz_id, vreme_polaska_time, aktivan) VALUES (7, 2, N'09:30:00', 1);
INSERT INTO ZelezniceSrbije.dbo.RasporedSablon (linija_id, voz_id, vreme_polaska_time, aktivan) VALUES (7, 1, N'19:30:00', 1);
INSERT INTO ZelezniceSrbije.dbo.RasporedSablon (linija_id, voz_id, vreme_polaska_time, aktivan) VALUES (8, 1, N'06:30:00', 1);
INSERT INTO ZelezniceSrbije.dbo.RasporedSablon (linija_id, voz_id, vreme_polaska_time, aktivan) VALUES (8, 2, N'12:30:00', 1);
INSERT INTO ZelezniceSrbije.dbo.RasporedSablon (linija_id, voz_id, vreme_polaska_time, aktivan) VALUES (8, 1, N'18:30:00', 1);
INSERT INTO ZelezniceSrbije.dbo.RasporedSablon (linija_id, voz_id, vreme_polaska_time, aktivan) VALUES (9, 2, N'07:30:00', 1);
INSERT INTO ZelezniceSrbije.dbo.RasporedSablon (linija_id, voz_id, vreme_polaska_time, aktivan) VALUES (9, 1, N'13:30:00', 1);
INSERT INTO ZelezniceSrbije.dbo.RasporedSablon (linija_id, voz_id, vreme_polaska_time, aktivan) VALUES (9, 2, N'19:30:00', 1);
INSERT INTO ZelezniceSrbije.dbo.RasporedSablon (linija_id, voz_id, vreme_polaska_time, aktivan) VALUES (10, 1, N'07:00:00', 1);
INSERT INTO ZelezniceSrbije.dbo.RasporedSablon (linija_id, voz_id, vreme_polaska_time, aktivan) VALUES (10, 2, N'14:00:00', 1);
INSERT INTO ZelezniceSrbije.dbo.RasporedSablon (linija_id, voz_id, vreme_polaska_time, aktivan) VALUES (11, 2, N'09:00:00', 1);
INSERT INTO ZelezniceSrbije.dbo.RasporedSablon (linija_id, voz_id, vreme_polaska_time, aktivan) VALUES (11, 1, N'16:00:00', 1);
INSERT INTO ZelezniceSrbije.dbo.RasporedSablon (linija_id, voz_id, vreme_polaska_time, aktivan) VALUES (12, 1, N'08:00:00', 1);
INSERT INTO ZelezniceSrbije.dbo.RasporedSablon (linija_id, voz_id, vreme_polaska_time, aktivan) VALUES (12, 2, N'16:00:00', 1);
INSERT INTO ZelezniceSrbije.dbo.RasporedSablon (linija_id, voz_id, vreme_polaska_time, aktivan) VALUES (13, 2, N'10:15:00', 1);
INSERT INTO ZelezniceSrbije.dbo.RasporedSablon (linija_id, voz_id, vreme_polaska_time, aktivan) VALUES (13, 1, N'18:15:00', 1);
INSERT INTO ZelezniceSrbije.dbo.RasporedSablon (linija_id, voz_id, vreme_polaska_time, aktivan) VALUES (14, 1, N'07:45:00', 1);
INSERT INTO ZelezniceSrbije.dbo.RasporedSablon (linija_id, voz_id, vreme_polaska_time, aktivan) VALUES (14, 2, N'13:45:00', 1);
INSERT INTO ZelezniceSrbije.dbo.RasporedSablon (linija_id, voz_id, vreme_polaska_time, aktivan) VALUES (15, 2, N'10:00:00', 1);
INSERT INTO ZelezniceSrbije.dbo.RasporedSablon (linija_id, voz_id, vreme_polaska_time, aktivan) VALUES (15, 1, N'16:00:00', 1);
INSERT INTO ZelezniceSrbije.dbo.RasporedSablon (linija_id, voz_id, vreme_polaska_time, aktivan) VALUES (16, 1, N'06:00:00', 1);
INSERT INTO ZelezniceSrbije.dbo.RasporedSablon (linija_id, voz_id, vreme_polaska_time, aktivan) VALUES (16, 2, N'14:15:00', 1);
INSERT INTO ZelezniceSrbije.dbo.RasporedSablon (linija_id, voz_id, vreme_polaska_time, aktivan) VALUES (17, 2, N'09:45:00', 1);
INSERT INTO ZelezniceSrbije.dbo.RasporedSablon (linija_id, voz_id, vreme_polaska_time, aktivan) VALUES (17, 1, N'18:00:00', 1);
INSERT INTO ZelezniceSrbije.dbo.RasporedSablon (linija_id, voz_id, vreme_polaska_time, aktivan) VALUES (18, 1, N'07:10:00', 1);
INSERT INTO ZelezniceSrbije.dbo.RasporedSablon (linija_id, voz_id, vreme_polaska_time, aktivan) VALUES (18, 2, N'15:10:00', 1);
INSERT INTO ZelezniceSrbije.dbo.RasporedSablon (linija_id, voz_id, vreme_polaska_time, aktivan) VALUES (19, 2, N'09:00:00', 1);
INSERT INTO ZelezniceSrbije.dbo.RasporedSablon (linija_id, voz_id, vreme_polaska_time, aktivan) VALUES (19, 1, N'17:00:00', 1);
INSERT INTO ZelezniceSrbije.dbo.RasporedSablon (linija_id, voz_id, vreme_polaska_time, aktivan) VALUES (20, 1, N'08:30:00', 1);
INSERT INTO ZelezniceSrbije.dbo.RasporedSablon (linija_id, voz_id, vreme_polaska_time, aktivan) VALUES (20, 2, N'20:30:00', 1);
GO

DECLARE @DatumOd DATETIME = GETDATE();
DECLARE @DatumDo DATETIME = DATEADD(DAY, 30, @DatumOd);

EXEC dbo.sp_GenerisiRasporede
    @Od = @DatumOd,
    @Do = @DatumDo;
GO